# docker-compose.yml
services:
  receipt-processor:
    build: .
    container_name: receipt_processor_app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
